from .auth_exception import AuthException